In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

C:\Users\User\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\User\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
raw_sessions = pd.read_csv("sessions.csv")
raw_sessions.head()

,user_id,action,action_type,action_detail,device_type,secs_elapsed
0,d1mm9tcy42,lookup,NaN,NaN,Windows Desktop,319.0
1,d1mm9tcy42,search_results,click,view_search_results,Windows Desktop,67753.0
2,d1mm9tcy42,lookup,NaN,NaN,Windows Desktop,301.0
3,d1mm9tcy42,search_results,click,view_search_results,Windows Desktop,22141.0
4,d1mm9tcy42,lookup,NaN,NaN,Windows Desktop,435.0

In [3]:
total_cat_action_detail = raw_sessions['action_detail'].value_counts()

In [4]:
"""
def group_action_detail(action):
    alphabets = str(action).lower()
    if alphabets in ['nan', '-unknown-']:
        return 'unknown'
    
    if any(x in alphabets for x in ['delete', 'cancel', 'remove', 'deactivate']):
        return 'account_maintenance'
    
    if any(x in alphabets for x in ['checkout', 'payment_instruments', 'apply_coupon']):
        return 'checkout_action'
    
    if any(x in alphabets for x in ['book', 'confirm', 'reserve', 'request_new_confirm']):
        return 'booking_intent'
    
    if any(x in alphabets for x in ['p3', 'p4', 'p5', 'view_listing', 'listing_details', 'photos']):
        return 'listing_view'
    
    if any(x in alphabets for x in ['search', 'results', 'lookup', 'similar', 'map']):
        return 'discovery'
    
    if any(x in alphabets for x in ['wishlist', 'message', 'contact', 'social', 'reviews', 'share']):
        return 'engagement'
    
    if any(x in alphabets for x in ['profile', 'login', 'signup', 'verif', 'account', 'settings']):
        return 'user_management'
    
    if 'host' in alphabets:
        return 'host_related'
    
    return 'other_actions'
"""

"\ndef group_action_detail(action):\n    alphabets = str(action).lower()\n    if alphabets in ['nan', '-unknown-']:\n        return 'unknown'\n    \n    if any(x in alphabets for x in ['delete', 'cancel', 'remove', 'deactivate']):\n        return 'account_maintenance'\n    \n    if any(x in alphabets for x in ['checkout', 'payment_instruments', 'apply_coupon']):\n        return 'checkout_action'\n    \n    if any(x in alphabets for x in ['book', 'confirm', 'reserve', 'request_new_confirm']):\n        return 'booking_intent'\n    \n    if any(x in alphabets for x in ['p3', 'p4', 'p5', 'view_listing', 'listing_details', 'photos']):\n        return 'listing_view'\n    \n    if any(x in alphabets for x in ['search', 'results', 'lookup', 'similar', 'map']):\n        return 'discovery'\n    \n    if any(x in alphabets for x in ['wishlist', 'message', 'contact', 'social', 'reviews', 'share']):\n        return 'engagement'\n    \n    if any(x in alphabets for x in ['profile', 'login', 'signup', 'verif', 'account', 'settings']):\n        return 'user_management'\n    \n    if 'host' in alphabets:\n        return 'host_related'\n    \n    return 'other_actions'\n"

In [5]:
raw_sessions['action_type'].value_counts()

action_type
view                3560902
data                2103770
click               1996183
-unknown-           1031170
submit               623357
message_post          87103
partner_callback      19132
booking_request       18773
modify                 1139
booking_response          4
Name: count, dtype: int64

In [6]:
raw_sessions[raw_sessions['action_type'] == 'submit']['action_detail'].value_counts()

action_detail
update_listing                    269779
create_user                        54878
contact_host                       44063
login                              38378
notifications                      32735
update_user                        29008
create_phone_numbers               28336
update_listing_description         26980
update_user_profile                26689
signup                             21494
apply_coupon                       10915
oauth_login                        10111
post_checkout_action                8867
send_message                        8528
create_listing                      7958
delete_phone_numbers                1241
wishlist_note                        961
set_password                         756
guest_cancellation                   583
email_wishlist                       319
forgot_password                      226
change_password                      172
delete_listing                       112
create_payment_instrument             86
calculate_worth                       56
change_availability                   42
create_alteration_request             27
set_default_payment_instrument        19
respond_to_alteration_request         11
deactivate_user_account                9
delete_listing_description             6
delete_payment_instrument              6
host_respond                           4
host_refund_guest                      2
Name: count, dtype: int64

In [7]:
raw_sessions[raw_sessions['action_type'] == 'booking_request']['action_detail'].value_counts()

action_detail
pending          13603
at_checkpoint     5170
Name: count, dtype: int64

In [8]:
raw_sessions[raw_sessions['action_type'] == 'view']['action_detail'].value_counts()

action_detail
p3                               1376550
user_profile                      656839
view_search_results               519675
dashboard                         152952
user_wishlists                    152672
message_thread                    132395
edit_profile                      108686
p5                                 48167
your_trips                         38195
p1                                 37976
profile_verifications              33434
user_listings                      31971
your_listings                      30980
p4                                 28030
manage_listing                     26618
account_notification_settings      21802
cancellation_policies              19262
message_inbox                      18718
view_listing                       18474
list_your_space                    14098
wishlist                           12308
profile_references                 11395
view_reservations                   9460
login_page                          9362
signup_login_page                   8408
view_locations                      7854
listing_descriptions                5735
account_payout_preferences          4569
popular_wishlists                   2160
host_home                           2103
account_transaction_history         2033
login_modal                         1977
terms_and_privacy                   1944
account_privacy_settings            1943
guest_itinerary                     1870
signup_modal                        1831
profile_reviews                     1292
your_reservations                   1283
change_or_alter                     1116
account_payment_methods             1005
set_password_page                    816
friends_wishlists                    804
previous_trips                       675
guest_receipt                        459
airbnb_picks_wishlists               278
host_guarantee                       248
view_security_checks                 135
place_worth                          108
view_identity_verifications           57
view_resolutions                      42
alteration_request                    42
view_user_real_names                  38
view_ghosting_reasons                 19
view_ghostings                        19
homepage                              15
tos_2014                               2
host_respond_page                      2
host_standard_suspension               1
Name: count, dtype: int64

In [9]:
raw_sessions[raw_sessions['action_type'] == 'data']['action_detail'].value_counts()

action_detail
wishlist_content_update        706824
similar_listings               364624
user_social_connections        336799
listing_reviews                269021
header_userpic                 141830
unavailable_dates               77795
user_profile_content_update     50434
user_reviews                    49665
reservations                    32479
listing_recommendations         30215
payment_instruments             23483
trip_availability                8550
notifications                    4620
user_tax_forms                   2633
lookup_message_thread            1793
user_languages                   1475
admin_templates                   835
user_friend_recommendations       375
translations                      320
Name: count, dtype: int64

In [10]:
raw_sessions[raw_sessions['action_type'] == 'click']['action_detail'].value_counts()

action_detail
view_search_results            1257210
change_trip_characteristics     487744
confirm_email_link               58422
change_contact_host_dates        52517
contact_host                     36978
message_to_host_focus            21636
message_to_host_change           14224
book_it                           8085
request_new_confirm_email         7933
coupon_field_focus                7608
apply_coupon_click                6223
apply_coupon_error                5566
read_policy_click                 3905
listing_reviews_page              3869
cancellation_policy_click         3461
instant_book                      3061
coupon_code_click                 2947
photos                            2904
request_to_book                   2833
phone_verification_success        2032
translate_listing_reviews          951
click_reviews                      925
click_about_host                   773
forgot_password                    534
move_map                           460
click_amenities                    426
email_wishlist_button              388
toggle_archived_thread             380
p4_refund_policy_terms             370
apply_coupon_click_success         329
confirm_email                      302
p4_terms                           292
toggle_starred_thread              206
alteration_field                   175
cancellation_policy                162
share                              160
remove_dashboard_alert             114
complete_booking                    75
special_offer_field                  3
Name: count, dtype: int64

In [11]:
raw_sessions[raw_sessions['action_type'] == '-unknown-']['action_detail'].value_counts()

action_detail
-unknown-        1031141
phone_numbers         27
reservations           2
Name: count, dtype: int64

In [12]:
raw_sessions[raw_sessions['action_type'] == 'message_post']['action_detail'].value_counts()

action_detail
message_post    87103
Name: count, dtype: int64

In [13]:
raw_sessions[raw_sessions['action_type'] == 'partner_callback']['action_detail'].value_counts()

action_detail
oauth_response    19132
Name: count, dtype: int64

In [14]:
raw_sessions[raw_sessions['action_type'] == 'modify']['action_detail'].value_counts()

action_detail
modify_users           688
modify_reservations    451
Name: count, dtype: int64

In [15]:
raw_sessions[raw_sessions['action_type'] == 'booking_response']['action_detail'].value_counts()

action_detail
booking    4
Name: count, dtype: int64

In [16]:
raw_sessions1 = raw_sessions.copy(deep = True)

In [17]:
def group_action_details(df):
    detail_map = {
        # --- Search & Discovery ---
        'view_search_results': 'search',
        'change_trip_characteristics': 'search',
        'move_map': 'search',
        'photos': 'search',
        'p3': 'search',
        'p1': 'search',
        'view_listing': 'search',
        'view_locations': 'search',
        'homepage': 'search',
        'unavailable_dates': 'search',
        'header_userpic': 'search',
        'translations': 'search',
        
        # --- Engagement ---
        'listing_reviews_page': 'engagement',
        'click_reviews': 'engagement',
        'translate_listing_reviews': 'engagement',
        'click_about_host': 'engagement',
        'click_amenities': 'engagement',
        'share': 'engagement',
        'wishlist_note': 'engagement',
        'calculate_worth': 'engagement',
        'user_wishlists': 'engagement',
        'p5': 'engagement',
        'wishlist': 'engagement',
        'profile_references': 'engagement',
        'listing_descriptions': 'engagement',
        'profile_reviews': 'engagement',
        'wishlist_content_update': 'engagement',
        'similar_listings': 'engagement',
        'listing_reviews': 'engagement',
        'user_profile_content_update': 'engagement',
        'user_reviews': 'engagement',
        'listing_recommendations': 'engagement',
        'trip_availability': 'engagement',
        
        # --- Account ---
        'confirm_email_link': 'account',
        'request_new_confirm_email': 'account',
        'confirm_email': 'account',
        'phone_verification_success': 'account',
        'create_user': 'account',
        'login': 'account',
        'signup': 'account',
        'update_user': 'account',
        'update_user_profile': 'account',
        'create_phone_numbers': 'account',
        'oauth_login': 'account',
        'set_password': 'account',
        'forgot_password': 'account',
        'change_password': 'account',
        'delete_phone_numbers': 'account',
        'deactivate_user_account': 'account',
        'user_profile': 'account',
        'dashboard': 'account',
        'edit_profile': 'account',
        'profile_verifications': 'account',
        'account_notification_settings': 'account',
        'login_page': 'account',
        'signup_login_page': 'account',
        'view_user_real_names': 'account',
        'user_social_connections': 'account',
        'payment_instruments': 'account',
        'user_tax_forms': 'account',
        'user_languages': 'account',
        'user_friend_recommendations': 'account',
        'oauth_response': 'account',
        'modify_users': 'account',
        'phone_numbers': 'account',
        
        # --- Pre-Booking/Booking ---
        'book_it': 'booking_flow',
        'request_to_book': 'booking_flow',
        'instant_book': 'booking_flow',
        'complete_booking': 'booking_flow',
        'coupon_field_focus': 'booking_flow',
        'apply_coupon_click': 'booking_flow',
        'apply_coupon_click_success': 'booking_flow',
        'coupon_code_click': 'booking_flow',
        'p4_terms': 'booking_flow',
        'p4_refund_policy_terms': 'booking_flow',
        'read_policy_click': 'booking_flow',
        'cancellation_policy_click': 'booking_flow',
        'apply_coupon': 'booking_flow',
        'post_checkout_action': 'booking_flow',
        'guest_cancellation': 'booking_flow',
        'create_payment_instrument': 'booking_flow',
        'set_default_payment_instrument': 'booking_flow',
        'create_alteration_request': 'booking_flow',
        'respond_to_alteration_request': 'booking_flow',
        'delete_payment_instrument': 'booking_flow',
        'pending': 'booking_flow',
        'at_checkpoint': 'booking_flow',
        'your_trips': 'booking_flow',
        'p4': 'booking_flow',
        'cancellation_policies': 'booking_flow',
        'view_reservations': 'booking_flow',
        'guest_itinerary': 'booking_flow',
        'account_payment_methods': 'booking_flow',
        'guest_receipt': 'booking_flow',
        'modify_reservations': 'booking_flow',
        'booking': 'booking_flow',
        'reservations': 'booking_flow',
        
        # --- Communication ---
        'contact_host': 'communication',
        'message_to_host_focus': 'communication',
        'message_to_host_change': 'communication',
        'change_contact_host_dates': 'communication',
        'send_message': 'communication',
        'email_wishlist': 'communication',
        'message_thread': 'communication',
        'message_inbox': 'communication',
        'lookup_message_thread': 'communication',
        'notifications': 'communication',
        'message_post': 'communication',
        
        # --- Host Side ---
        'update_listing': 'host_action',
        'create_listing': 'host_action',
        'update_listing_description': 'host_action',
        'delete_listing': 'host_action',
        'change_availability': 'host_action',
        'host_respond': 'host_action',
        'host_refund_guest': 'host_action',
        'delete_listing_description': 'host_action',
        'user_listings': 'host_action',
        'your_listings': 'host_action',
        'manage_listing': 'host_action',
        'list_your_space': 'host_action',
        'host_home': 'host_action',
        
        '-unknown-': 'unknown',
    }
    
    df['detail_group'] = df['action_detail'].map(detail_map).fillna('other')
    
    return df

In [18]:
raw_sessions1 = group_action_details(raw_sessions1)

In [19]:
raw_sessions1.head()

,user_id,action,action_type,action_detail,device_type,secs_elapsed,detail_group
0,d1mm9tcy42,lookup,NaN,NaN,Windows Desktop,319.0,other
1,d1mm9tcy42,search_results,click,view_search_results,Windows Desktop,67753.0,search
2,d1mm9tcy42,lookup,NaN,NaN,Windows Desktop,301.0,other
3,d1mm9tcy42,search_results,click,view_search_results,Windows Desktop,22141.0,search
4,d1mm9tcy42,lookup,NaN,NaN,Windows Desktop,435.0,other

In [20]:
raw_sessions2 = raw_sessions1.copy(deep = True)

In [21]:
total_sessions_table = raw_sessions2.groupby('user_id').size().reset_index(name = 'total_sessions')
total_sessions_table.head()

      user_id  total_sessions
0  00023iyk9l              40
1  0010k6l0om              63
2  001wyh0pz8              90
3  0028jgx1x1              31
4  002qnbzfs5             789

In [22]:
total_sessions_table['user_id'].nunique()

135483

In [23]:
raw_sessions2['user_id'].nunique()

135483

In [24]:
booking_table = raw_sessions2[raw_sessions2['detail_group'] == 'booking_flow'].groupby('user_id').size().reset_index(name = 'booking_counts') 
booking_table['is_booking'] = (booking_table['booking_counts'] > 0).astype(int)
booking_table.head()

      user_id  booking_counts  is_booking
0  00023iyk9l               3           1
1  002qnbzfs5              27           1
2  00378ocvlh               1           1
3  003iamz20l               2           1
4  0048rkdgb1               1           1

In [25]:
booking_table['user_id'].nunique()

47392

In [26]:
new_sessions_table = total_sessions_table.merge(booking_table, how = 'left', on = 'user_id')
print('Current missing values before imputation:\n', new_sessions_table.isna().sum())
new_sessions_table = new_sessions_table.fillna(0)
print('\nCurrent missing values after imputation:\n', new_sessions_table.isna().sum())
print('\n', new_sessions_table.head())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values before imputation:
 user_id               0
total_sessions        0
booking_counts    88091
is_booking        88091
dtype: int64

Current missing values after imputation:
 user_id           0
total_sessions    0
booking_counts    0
is_booking        0
dtype: int64

       user_id  total_sessions  booking_counts  is_booking
0  00023iyk9l              40             3.0         1.0
1  0010k6l0om              63             0.0         0.0
2  001wyh0pz8              90             0.0         0.0
3  0028jgx1x1              31             0.0         0.0
4  002qnbzfs5             789            27.0         1.0

There are  135483  of observations.

In [27]:
abandon_list = ['guest_cancellation', 'delete_payment_instrument', 'create_alteration_request']
abandon_table = raw_sessions2[raw_sessions2['action_detail'].isin(abandon_list)].groupby('user_id').size().reset_index(name = 'abandon_freq') 
new_sessions_table = new_sessions_table.merge(abandon_table, how = 'left', on = 'user_id') 
new_sessions_table['regret_ratio'] = new_sessions_table['abandon_freq']/(new_sessions_table['booking_counts'] + 0.0001) 
print('Current missing values before imputation:\n', new_sessions_table.isna().sum())
new_sessions_table['regret_ratio'] = new_sessions_table['regret_ratio'].fillna(0)
new_sessions_table['abandon_freq'] = new_sessions_table['abandon_freq'].fillna(0).astype(int)
print('\nCurrent missing values after imputation:\n', new_sessions_table.isna().sum())
print('\n', new_sessions_table.head())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values before imputation:
 user_id                0
total_sessions         0
booking_counts         0
is_booking             0
abandon_freq      134946
regret_ratio      134946
dtype: int64

Current missing values after imputation:
 user_id           0
total_sessions    0
booking_counts    0
is_booking        0
abandon_freq      0
regret_ratio      0
dtype: int64

       user_id  total_sessions  booking_counts  is_booking  abandon_freq  \
0  00023iyk9l              40             3.0         1.0             0
1  0010k6l0om              63             0.0         0.0             0
2  001wyh0pz8              90             0.0         0.0             0
3  0028jgx1x1              31             0.0         0.0             0
4  002qnbzfs5             789            27.0         1.0             0

   regret_ratio
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0

There are  135483  of observations.

In [28]:
new_sessions_table['booking_intent_rate'] = new_sessions_table['booking_counts']/(new_sessions_table['total_sessions'] + 0.0001)
new_sessions_table['conversion_rate'] = (new_sessions_table['booking_counts'] - new_sessions_table['abandon_freq'])/new_sessions_table['total_sessions']
print('Current missing values:\n', new_sessions_table.isna().sum())
print('\n', new_sessions_table.head())

Current missing values:
 user_id                0
total_sessions         0
booking_counts         0
is_booking             0
abandon_freq           0
regret_ratio           0
booking_intent_rate    0
conversion_rate        0
dtype: int64

       user_id  total_sessions  booking_counts  is_booking  abandon_freq  \
0  00023iyk9l              40             3.0         1.0             0
1  0010k6l0om              63             0.0         0.0             0
2  001wyh0pz8              90             0.0         0.0             0
3  0028jgx1x1              31             0.0         0.0             0
4  002qnbzfs5             789            27.0         1.0             0

   regret_ratio  booking_intent_rate  conversion_rate
0           0.0             0.075000         0.075000
1           0.0             0.000000         0.000000
2           0.0             0.000000         0.000000
3           0.0             0.000000         0.000000
4           0.0             0.034221         0.034221

In [29]:
# clicks before booking = total of view and search
total_searches_table = raw_sessions2[raw_sessions2['detail_group'] == 'search'].groupby('user_id').size().reset_index(name = 'total_searches')
total_engage_table = raw_sessions2[raw_sessions2['detail_group'] == 'engagement'].groupby('user_id').size().reset_index(name = 'total_engagement')
total_communicate_table = raw_sessions2[raw_sessions2['detail_group'] == 'communication'].groupby('user_id').size().reset_index(name = 'total_communication')

In [30]:
total_searches_table.shape

(128167, 2)

In [31]:
total_engage_table.shape

(110893, 2)

In [32]:
total_communicate_table.shape

(73841, 2)

In [33]:
clicks_before_booking_table = total_searches_table.merge(total_engage_table, how = 'outer', on = 'user_id')

In [34]:
clicks_before_booking_table = clicks_before_booking_table.merge(total_communicate_table, how = 'outer', on = 'user_id')
clicks_before_booking_table.head()

      user_id  total_searches  total_engagement  total_communication
0  00023iyk9l            15.0              12.0                  1.0
1  0010k6l0om            32.0               8.0                  NaN
2  001wyh0pz8            68.0               4.0                  1.0
3  0028jgx1x1            18.0               5.0                  NaN
4  002qnbzfs5           173.0              13.0                 78.0

In [35]:
print('Current missing values before imputation:\n', clicks_before_booking_table.isna().sum())
clicks_before_booking_table = clicks_before_booking_table.fillna(0)
print('\nCurrent missing values after imputation:\n', clicks_before_booking_table.isna().sum())

clicks_before_booking_table['total_evaluation'] = clicks_before_booking_table['total_engagement'] + clicks_before_booking_table['total_communication']

new_sessions_table = new_sessions_table.merge(clicks_before_booking_table, how = 'left', on = 'user_id')
print('\nCurrent missing values before imputation:\n', new_sessions_table.isna().sum())
print('\n', new_sessions_table.head())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values before imputation:
 user_id                    0
total_searches          3727
total_engagement       21001
total_communication    58053
dtype: int64

Current missing values after imputation:
 user_id                0
total_searches         0
total_engagement       0
total_communication    0
dtype: int64

Current missing values before imputation:
 user_id                   0
total_sessions            0
booking_counts            0
is_booking                0
abandon_freq              0
regret_ratio              0
booking_intent_rate       0
conversion_rate           0
total_searches         3589
total_engagement       3589
total_communication    3589
total_evaluation       3589
dtype: int64

       user_id  total_sessions  booking_counts  is_booking  abandon_freq  \
0  00023iyk9l              40             3.0         1.0             0
1  0010k6l0om              63             0.0         0.0             0
2  001wyh0pz8              90             0.0         0.0             0
3  0028jgx1x1              31             0.0         0.0             0
4  002qnbzfs5             789            27.0         1.0             0

   regret_ratio  booking_intent_rate  conversion_rate  total_searches  \
0           0.0             0.075000         0.075000            15.0
1           0.0             0.000000         0.000000            32.0
2           0.0             0.000000         0.000000            68.0
3           0.0             0.000000         0.000000            18.0
4           0.0             0.034221         0.034221           173.0

   total_engagement  total_communication  total_evaluation
0              12.0                  1.0              13.0
1               8.0                  0.0               8.0
2               4.0                  1.0               5.0
3               5.0                  0.0               5.0
4              13.0                 78.0              91.0

There are  135483  of observations.

In [36]:
new_sessions_table = new_sessions_table.fillna(0)

new_sessions_table['decision_complexity'] = (new_sessions_table['total_searches'] + new_sessions_table['total_evaluation'])/(new_sessions_table['booking_counts'] + 0.0001)
print('Current missing values:\n', new_sessions_table.isna().sum())
print('\n', new_sessions_table.head())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values:
 user_id                0
total_sessions         0
booking_counts         0
is_booking             0
abandon_freq           0
regret_ratio           0
booking_intent_rate    0
conversion_rate        0
total_searches         0
total_engagement       0
total_communication    0
total_evaluation       0
decision_complexity    0
dtype: int64

       user_id  total_sessions  booking_counts  is_booking  abandon_freq  \
0  00023iyk9l              40             3.0         1.0             0
1  0010k6l0om              63             0.0         0.0             0
2  001wyh0pz8              90             0.0         0.0             0
3  0028jgx1x1              31             0.0         0.0             0
4  002qnbzfs5             789            27.0         1.0             0

   regret_ratio  booking_intent_rate  conversion_rate  total_searches  \
0           0.0             0.075000         0.075000            15.0
1           0.0             0.000000         0.000000            32.0
2           0.0             0.000000         0.000000            68.0
3           0.0             0.000000         0.000000            18.0
4           0.0             0.034221         0.034221           173.0

   total_engagement  total_communication  total_evaluation  \
0              12.0                  1.0              13.0
1               8.0                  0.0               8.0
2               4.0                  1.0               5.0
3               5.0                  0.0               5.0
4              13.0                 78.0              91.0

   decision_complexity
0             9.333022
1        400000.000000
2        730000.000000
3        230000.000000
4             9.777742

There are  135483  of observations.

In [37]:
new_sessions_table.loc[new_sessions_table['booking_counts'] == 0, 'decision_complexity'] = 0
new_sessions_table.head()

,user_id,total_sessions,booking_counts,is_booking,abandon_freq,regret_ratio,booking_intent_rate,conversion_rate,total_searches,total_engagement,total_communication,total_evaluation,decision_complexity
0,00023iyk9l,40,3.0,1.0,0,0.0,0.075000,0.075000,15.0,12.0,1.0,13.0,9.333022
1,0010k6l0om,63,0.0,0.0,0,0.0,0.000000,0.000000,32.0,8.0,0.0,8.0,0.000000
2,001wyh0pz8,90,0.0,0.0,0,0.0,0.000000,0.000000,68.0,4.0,1.0,5.0,0.000000
3,0028jgx1x1,31,0.0,0.0,0,0.0,0.000000,0.000000,18.0,5.0,0.0,5.0,0.000000
4,002qnbzfs5,789,27.0,1.0,0,0.0,0.034221,0.034221,173.0,13.0,78.0,91.0,9.777742

In [38]:
new_sessions_table['has_regretted'] = (new_sessions_table['regret_ratio'] > 0).astype(int) 
new_sessions_table.head()

,user_id,total_sessions,booking_counts,is_booking,abandon_freq,regret_ratio,booking_intent_rate,conversion_rate,total_searches,total_engagement,total_communication,total_evaluation,decision_complexity,has_regretted
0,00023iyk9l,40,3.0,1.0,0,0.0,0.075000,0.075000,15.0,12.0,1.0,13.0,9.333022,0
1,0010k6l0om,63,0.0,0.0,0,0.0,0.000000,0.000000,32.0,8.0,0.0,8.0,0.000000,0
2,001wyh0pz8,90,0.0,0.0,0,0.0,0.000000,0.000000,68.0,4.0,1.0,5.0,0.000000,0
3,0028jgx1x1,31,0.0,0.0,0,0.0,0.000000,0.000000,18.0,5.0,0.0,5.0,0.000000,0
4,002qnbzfs5,789,27.0,1.0,0,0.0,0.034221,0.034221,173.0,13.0,78.0,91.0,9.777742,0

In [39]:
# friction feature
friction_list = ['apply_coupon_error', 'at_checkpoint', 'profile_verifications', 
                 'account_payout_preferences', 'change_password', 'forgot_password']
friction_table = raw_sessions2[raw_sessions2['action_detail'].isin(friction_list)].groupby('user_id').size().reset_index(name = 'friction_freq')
friction_table['friction_freq'] = friction_table['friction_freq'].fillna(0)
friction_table.head()

      user_id  friction_freq
0  002qnbzfs5              1
1  00389675gq              4
2  006z8b0uws              2
3  00bn6hu437              2
4  00bxmflswn              2

In [40]:
new_sessions_table = new_sessions_table.merge(friction_table, how = 'left', on = 'user_id')
print('Current missing values before imputation:\n', new_sessions_table.isna().sum())
new_sessions_table = new_sessions_table.fillna(0)
print('\nCurrent missing values after:\n', new_sessions_table.isna().sum())
print('\n', new_sessions_table.head())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values before imputation:
 user_id                     0
total_sessions              0
booking_counts              0
is_booking                  0
abandon_freq                0
regret_ratio                0
booking_intent_rate         0
conversion_rate             0
total_searches              0
total_engagement            0
total_communication         0
total_evaluation            0
decision_complexity         0
has_regretted               0
friction_freq          120257
dtype: int64

Current missing values after:
 user_id                0
total_sessions         0
booking_counts         0
is_booking             0
abandon_freq           0
regret_ratio           0
booking_intent_rate    0
conversion_rate        0
total_searches         0
total_engagement       0
total_communication    0
total_evaluation       0
decision_complexity    0
has_regretted          0
friction_freq          0
dtype: int64

       user_id  total_sessions  booking_counts  is_booking  abandon_freq  \
0  00023iyk9l              40             3.0         1.0             0
1  0010k6l0om              63             0.0         0.0             0
2  001wyh0pz8              90             0.0         0.0             0
3  0028jgx1x1              31             0.0         0.0             0
4  002qnbzfs5             789            27.0         1.0             0

   regret_ratio  booking_intent_rate  conversion_rate  total_searches  \
0           0.0             0.075000         0.075000            15.0
1           0.0             0.000000         0.000000            32.0
2           0.0             0.000000         0.000000            68.0
3           0.0             0.000000         0.000000            18.0
4           0.0             0.034221         0.034221           173.0

   total_engagement  total_communication  total_evaluation  \
0              12.0                  1.0              13.0
1               8.0                  0.0               8.0
2               4.0                  1.0               5.0
3               5.0                  0.0               5.0
4              13.0                 78.0              91.0

   decision_complexity  has_regretted  friction_freq
0             9.333022              0            0.0
1             0.000000              0            0.0
2             0.000000              0            0.0
3             0.000000              0            0.0
4             9.777742              0            1.0

There are  135483  of observations.

In [41]:
browsing_table1 = raw_sessions2[raw_sessions2['action_detail'] == 'p3'].groupby('user_id').size().reset_index(name = 'p3_freq')
browsing_table2 = raw_sessions2[raw_sessions2['action_detail'] == 'view_search_results'].groupby('user_id').size().reset_index(name = 'view_search_freq')
browsing_table = browsing_table1.merge(browsing_table2, how = 'outer', on = 'user_id') 
browsing_table = browsing_table.fillna(0)
browsing_table['browsing_depth'] = browsing_table['p3_freq']/(browsing_table['view_search_freq'] + 0.0001)
browsing_table.head()

      user_id  p3_freq  view_search_freq  browsing_depth
0  00023iyk9l      6.0               5.0        1.199976
1  0010k6l0om     13.0              10.0        1.299987
2  001wyh0pz8      2.0              66.0        0.030303
3  0028jgx1x1      9.0               9.0        0.999989
4  002qnbzfs5     25.0             125.0        0.200000

In [42]:
new_sessions_table = new_sessions_table.merge(browsing_table, how = 'left', on = 'user_id')
print('Current missing values before imputation:\n', new_sessions_table.isna().sum())
new_sessions_table = new_sessions_table.fillna(0)
print('\nCurrent missing values after imputation:\n', new_sessions_table.isna().sum())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values before imputation:
 user_id                    0
total_sessions             0
booking_counts             0
is_booking                 0
abandon_freq               0
regret_ratio               0
booking_intent_rate        0
conversion_rate            0
total_searches             0
total_engagement           0
total_communication        0
total_evaluation           0
decision_complexity        0
has_regretted              0
friction_freq              0
p3_freq                33107
view_search_freq       33107
browsing_depth         33107
dtype: int64

Current missing values after imputation:
 user_id                0
total_sessions         0
booking_counts         0
is_booking             0
abandon_freq           0
regret_ratio           0
booking_intent_rate    0
conversion_rate        0
total_searches         0
total_engagement       0
total_communication    0
total_evaluation       0
decision_complexity    0
has_regretted          0
friction_freq          0
p3_freq                0
view_search_freq       0
browsing_depth         0
dtype: int64

There are  135483  of observations.

In [43]:
new_sessions_table.head()

,user_id,total_sessions,booking_counts,is_booking,abandon_freq,regret_ratio,booking_intent_rate,conversion_rate,total_searches,total_engagement,total_communication,total_evaluation,decision_complexity,has_regretted,friction_freq,p3_freq,view_search_freq,browsing_depth
0,00023iyk9l,40,3.0,1.0,0,0.0,0.075000,0.075000,15.0,12.0,1.0,13.0,9.333022,0,0.0,6.0,5.0,1.199976
1,0010k6l0om,63,0.0,0.0,0,0.0,0.000000,0.000000,32.0,8.0,0.0,8.0,0.000000,0,0.0,13.0,10.0,1.299987
2,001wyh0pz8,90,0.0,0.0,0,0.0,0.000000,0.000000,68.0,4.0,1.0,5.0,0.000000,0,0.0,2.0,66.0,0.030303
3,0028jgx1x1,31,0.0,0.0,0,0.0,0.000000,0.000000,18.0,5.0,0.0,5.0,0.000000,0,0.0,9.0,9.0,0.999989
4,002qnbzfs5,789,27.0,1.0,0,0.0,0.034221,0.034221,173.0,13.0,78.0,91.0,9.777742,0,1.0,25.0,125.0,0.200000

In [44]:
price_list = ['coupon_code_click', 'apply_coupon_click', 'apply_coupon_error', 'apply_coupon_click_success', 
                        'coupon_field_focus', 'apply_coupon']

price_table = raw_sessions2[raw_sessions2['action_detail'].isin(price_list)].groupby('user_id').size().reset_index(name = 'price_sensitive_freq')
price_table.head()

      user_id  price_sensitive_freq
0  00b9hfwaak                     2
1  00g52q8uim                     1
2  00lglrzikw                     2
3  01kv2ppj25                    14
4  01r3iatdvv                     1

In [45]:
new_sessions_table = new_sessions_table.merge(price_table, how = 'left', on = 'user_id')
print('Current missing values before imputation:\n', new_sessions_table.isna().sum())
new_sessions_table = new_sessions_table.fillna(0)
print('\nCurrent missing values after imputation:\n', new_sessions_table.isna().sum())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values before imputation:
 user_id                      0
total_sessions               0
booking_counts               0
is_booking                   0
abandon_freq                 0
regret_ratio                 0
booking_intent_rate          0
conversion_rate              0
total_searches               0
total_engagement             0
total_communication          0
total_evaluation             0
decision_complexity          0
has_regretted                0
friction_freq                0
p3_freq                      0
view_search_freq             0
browsing_depth               0
price_sensitive_freq    132521
dtype: int64

Current missing values after imputation:
 user_id                 0
total_sessions          0
booking_counts          0
is_booking              0
abandon_freq            0
regret_ratio            0
booking_intent_rate     0
conversion_rate         0
total_searches          0
total_engagement        0
total_communication     0
total_evaluation        0
decision_complexity     0
has_regretted           0
friction_freq           0
p3_freq                 0
view_search_freq        0
browsing_depth          0
price_sensitive_freq    0
dtype: int64

There are  135483  of observations.

In [46]:
new_sessions_table['price_intensity'] = new_sessions_table['price_sensitive_freq']/(new_sessions_table['total_sessions'] + 0.0001)

new_sessions_table['is_price_seeker'] = (new_sessions_table['price_sensitive_freq'] > 0).astype(int)

print('Current missing values:\n', new_sessions_table.isna().sum())

Current missing values:
 user_id                 0
total_sessions          0
booking_counts          0
is_booking              0
abandon_freq            0
regret_ratio            0
booking_intent_rate     0
conversion_rate         0
total_searches          0
total_engagement        0
total_communication     0
total_evaluation        0
decision_complexity     0
has_regretted           0
friction_freq           0
p3_freq                 0
view_search_freq        0
browsing_depth          0
price_sensitive_freq    0
price_intensity         0
is_price_seeker         0
dtype: int64

In [47]:
communicate_list = ['contact_host', 'send_message', 'message_post', 'message_to_host_focus', 
                    'message_to_host_change', 'change_contact_host_dates', 'email_wishlist']

communicate_table = raw_sessions2[raw_sessions2['action_detail'].isin(communicate_list)].groupby('user_id').size().reset_index(name = 'communicate_freq')
communicate_table.head()

      user_id  communicate_freq
0  00023iyk9l                 1
1  002qnbzfs5                24
2  0035hobuyj                10
3  00378ocvlh                 5
4  00389675gq                 8

In [48]:
new_sessions_table = new_sessions_table.merge(communicate_table, how = 'left', on = 'user_id')
print('Current missing values before imputation:\n', new_sessions_table.isna().sum())
new_sessions_table = new_sessions_table.fillna(0)
print('\nCurrent missing values after imputation:\n', new_sessions_table.isna().sum())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values before imputation:
 user_id                     0
total_sessions              0
booking_counts              0
is_booking                  0
abandon_freq                0
regret_ratio                0
booking_intent_rate         0
conversion_rate             0
total_searches              0
total_engagement            0
total_communication         0
total_evaluation            0
decision_complexity         0
has_regretted               0
friction_freq               0
p3_freq                     0
view_search_freq            0
browsing_depth              0
price_sensitive_freq        0
price_intensity             0
is_price_seeker             0
communicate_freq        87165
dtype: int64

Current missing values after imputation:
 user_id                 0
total_sessions          0
booking_counts          0
is_booking              0
abandon_freq            0
regret_ratio            0
booking_intent_rate     0
conversion_rate         0
total_searches          0
total_engagement        0
total_communication     0
total_evaluation        0
decision_complexity     0
has_regretted           0
friction_freq           0
p3_freq                 0
view_search_freq        0
browsing_depth          0
price_sensitive_freq    0
price_intensity         0
is_price_seeker         0
communicate_freq        0
dtype: int64

There are  135483  of observations.

In [49]:
new_sessions_table['communication_intensity'] = new_sessions_table['communicate_freq']/(new_sessions_table['total_sessions'] + 0.0001)

new_sessions_table['is_communicator'] = (new_sessions_table['communicate_freq'] > 0).astype(int)

print('Current missing values:\n', new_sessions_table.isna().sum())

Current missing values:
 user_id                    0
total_sessions             0
booking_counts             0
is_booking                 0
abandon_freq               0
regret_ratio               0
booking_intent_rate        0
conversion_rate            0
total_searches             0
total_engagement           0
total_communication        0
total_evaluation           0
decision_complexity        0
has_regretted              0
friction_freq              0
p3_freq                    0
view_search_freq           0
browsing_depth             0
price_sensitive_freq       0
price_intensity            0
is_price_seeker            0
communicate_freq           0
communication_intensity    0
is_communicator            0
dtype: int64

In [50]:
visual_list = ['photos', 'header_userpic', 'p3', 'p4']

visual_table = raw_sessions2[raw_sessions2['action_detail'].isin(visual_list)].groupby('user_id').size().reset_index(name = 'visual_freq')
visual_table.head()

      user_id  visual_freq
0  00023iyk9l            8
1  0010k6l0om           14
2  001wyh0pz8            2
3  0028jgx1x1            9
4  002qnbzfs5           27

In [51]:
new_sessions_table = new_sessions_table.merge(visual_table, how = 'left', on = 'user_id')
print('Current missing values before imputation:\n', new_sessions_table.isna().sum())
new_sessions_table = new_sessions_table.fillna(0)
print('\nCurrent missing values after imputation:\n', new_sessions_table.isna().sum())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values before imputation:
 user_id                        0
total_sessions                 0
booking_counts                 0
is_booking                     0
abandon_freq                   0
regret_ratio                   0
booking_intent_rate            0
conversion_rate                0
total_searches                 0
total_engagement               0
total_communication            0
total_evaluation               0
decision_complexity            0
has_regretted                  0
friction_freq                  0
p3_freq                        0
view_search_freq               0
browsing_depth                 0
price_sensitive_freq           0
price_intensity                0
is_price_seeker                0
communicate_freq               0
communication_intensity        0
is_communicator                0
visual_freq                11301
dtype: int64

Current missing values after imputation:
 user_id                    0
total_sessions             0
booking_counts             0
is_booking                 0
abandon_freq               0
regret_ratio               0
booking_intent_rate        0
conversion_rate            0
total_searches             0
total_engagement           0
total_communication        0
total_evaluation           0
decision_complexity        0
has_regretted              0
friction_freq              0
p3_freq                    0
view_search_freq           0
browsing_depth             0
price_sensitive_freq       0
price_intensity            0
is_price_seeker            0
communicate_freq           0
communication_intensity    0
is_communicator            0
visual_freq                0
dtype: int64

There are  135483  of observations.

In [52]:
new_sessions_table['visual_intensity'] = new_sessions_table['visual_freq']/(new_sessions_table['total_sessions'] + 0.0001)

new_sessions_table['is_visual'] = (new_sessions_table['visual_freq'] > 0).astype(int)

print('Current missing values:\n', new_sessions_table.isna().sum())

Current missing values:
 user_id                    0
total_sessions             0
booking_counts             0
is_booking                 0
abandon_freq               0
regret_ratio               0
booking_intent_rate        0
conversion_rate            0
total_searches             0
total_engagement           0
total_communication        0
total_evaluation           0
decision_complexity        0
has_regretted              0
friction_freq              0
p3_freq                    0
view_search_freq           0
browsing_depth             0
price_sensitive_freq       0
price_intensity            0
is_price_seeker            0
communicate_freq           0
communication_intensity    0
is_communicator            0
visual_freq                0
visual_intensity           0
is_visual                  0
dtype: int64

In [53]:
trust_list = ['user_social_connections', 'listing_reviews', 'profile_reviews', 'listing_reviews_page', 
              'user_reviews', 'profile_references']
trust_table = raw_sessions2[raw_sessions2['action_detail'].isin(trust_list)].groupby('user_id').size().reset_index(name = 'trust_freq')
trust_table['trust_freq'] = trust_table['trust_freq'].fillna(0)
trust_table.head()

      user_id  trust_freq
0  001wyh0pz8           2
1  0028jgx1x1           5
2  002qnbzfs5          85
3  00378ocvlh           2
4  00389675gq           3

In [54]:
new_sessions_table = new_sessions_table.merge(trust_table, how = 'left', on = 'user_id')
print('Current missing values before imputation:\n', new_sessions_table.isna().sum())
new_sessions_table = new_sessions_table.fillna(0)
print('\nCurrent missing values after imputation:\n', new_sessions_table.isna().sum())
print('\nThere are ', len(new_sessions_table), ' of observations.')

Current missing values before imputation:
 user_id                        0
total_sessions                 0
booking_counts                 0
is_booking                     0
abandon_freq                   0
regret_ratio                   0
booking_intent_rate            0
conversion_rate                0
total_searches                 0
total_engagement               0
total_communication            0
total_evaluation               0
decision_complexity            0
has_regretted                  0
friction_freq                  0
p3_freq                        0
view_search_freq               0
browsing_depth                 0
price_sensitive_freq           0
price_intensity                0
is_price_seeker                0
communicate_freq               0
communication_intensity        0
is_communicator                0
visual_freq                    0
visual_intensity               0
is_visual                      0
trust_freq                 95072
dtype: int64

Current missing values after imputation:
 user_id                    0
total_sessions             0
booking_counts             0
is_booking                 0
abandon_freq               0
regret_ratio               0
booking_intent_rate        0
conversion_rate            0
total_searches             0
total_engagement           0
total_communication        0
total_evaluation           0
decision_complexity        0
has_regretted              0
friction_freq              0
p3_freq                    0
view_search_freq           0
browsing_depth             0
price_sensitive_freq       0
price_intensity            0
is_price_seeker            0
communicate_freq           0
communication_intensity    0
is_communicator            0
visual_freq                0
visual_intensity           0
is_visual                  0
trust_freq                 0
dtype: int64

There are  135483  of observations.

In [55]:
new_sessions_table['trust_intensity'] = new_sessions_table['trust_freq']/(new_sessions_table['total_sessions'] + 0.0001)

new_sessions_table['is_trust_seeker'] = (new_sessions_table['trust_freq'] > 0).astype(int)

print('Current missing values:\n', new_sessions_table.isna().sum())

Current missing values:
 user_id                    0
total_sessions             0
booking_counts             0
is_booking                 0
abandon_freq               0
regret_ratio               0
booking_intent_rate        0
conversion_rate            0
total_searches             0
total_engagement           0
total_communication        0
total_evaluation           0
decision_complexity        0
has_regretted              0
friction_freq              0
p3_freq                    0
view_search_freq           0
browsing_depth             0
price_sensitive_freq       0
price_intensity            0
is_price_seeker            0
communicate_freq           0
communication_intensity    0
is_communicator            0
visual_freq                0
visual_intensity           0
is_visual                  0
trust_freq                 0
trust_intensity            0
is_trust_seeker            0
dtype: int64